[build]
  command = "pnpm install && pnpm run build"
  functions = "netlify/functions"
  publish = "dist/spa"


[functions]
  external_node_modules = ["express", "cors", "dotenv"]
  node_bundler = "esbuild"

[functions."api"]
  external_node_modules = ["express", "cors", "dotenv"]

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
